spring.application.name=web-rtc-backend

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/web-rtc-backend?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# JWT Configuration
app.jwt.secret=mySecretKey12345678901234567890123456789012345678901234567890
app.jwt.expiration=86400000

# Logging for debugging
logging.level.liquibase=DEBUG

# Cloudflare R2 (S3 compatible) configuration - values come from environment variables
r2.access-key-id=8c5cbbdb2c98d0101d72f22db3cac26b
r2.secret-access-key=efb384d8a90e48b641dc68029b2507749b266ef6169032c9b6f06d10a8d89bfe
r2.endpoint=https://72662c6c65b70e0f4cbc684c1e903275.r2.cloudflarestorage.com/web-rtc
r2.bucket-name=web-rtc
r2.region=auto

# AssemblyAI Configuration
assemblyai.api-key=${ASSEMBLYAI_API_KEY:dc62eb3902374d2fb83cc84616c1e715}
gemini.api-key=${GEMINI_API_KEY:AIzaSyDeCqK-quDSZMlXNpwKCJ_mjD34oCqN78o}
gemini.url=${GEMINI_URL:https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent}

# Redis Configuration (Railway public proxy)
spring.data.redis.host=crossover.proxy.rlwy.net
spring.data.redis.port=42345
spring.data.redis.username=default
spring.data.redis.password=HreohYZoONTKXmHrcLPFEslWcfpLwFex
spring.data.redis.timeout=30000
