spring.application.name=web-rtc-backend

server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000

logging.level.liquibase=DEBUG

r2.access-key-id=${R2_ACCESS_KEY}
r2.secret-access-key=${R2_SECRET_KEY}
r2.endpoint=${R2_ENDPOINT}
r2.bucket-name=${R2_BUCKET}
r2.region=${R2_REGION}

# AssemblyAI Configuration
assemblyai.api-key=${ASSEMBLYAI_API_KEY:dc62eb3902374d2fb83cc84616c1e715}
gemini.api-key=${GEMINI_API_KEY:AIzaSyDeCqK-quDSZMlXNpwKCJ_mjD34oCqN78o}
gemini.url=${GEMINI_URL:https://generativelanguage.googleapis.com/v1/models/gemini-2.5-pro:generateContent}

# Redis Configuration (Railway public proxy)
spring.data.redis.host=crossover.proxy.rlwy.net
spring.data.redis.port=42345
spring.data.redis.username=default
spring.data.redis.password=HreohYZoONTKXmHrcLPFEslWcfpLwFex
spring.data.redis.timeout=30000
