-- SQL Script để tạo bảng users nếu Liquibase không chạy được
-- Chạy script này trong MySQL Workbench hoặc command line

USE english_db;

-- Tạo bảng users
CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Tạo index
CREATE INDEX idx_users_role ON users(role);

-- Tạo bảng Liquibase tracking (nếu cần)
CREATE TABLE IF NOT EXISTS DATABASECHANGELOG (
    ID VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(255) NOT NULL,
    FILENAME VARCHAR(255) NOT NULL,
    DATEEXECUTED DATETIME NOT NULL,
    ORDEREXECUTED INT NOT NULL,
    EXECTYPE VARCHAR(10) NOT NULL,
    MD5SUM VARCHAR(35),
    DESCRIPTION VARCHAR(255),
    COMMENTS VARCHAR(255),
    TAG VARCHAR(255),
    LIQUIBASE VARCHAR(20),
    CONTEXTS VARCHAR(255),
    LABELS VARCHAR(255),
    DEPLOYMENT_ID VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS DATABASECHANGELOGLOCK (
    ID INT NOT NULL PRIMARY KEY,
    LOCKED TINYINT(1) NOT NULL,
    LOCKGRANTED DATETIME,
    LOCKEDBY VARCHAR(255)
);

-- Insert lock record
INSERT IGNORE INTO DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, 0);

SELECT 'Tables created successfully!' as result;

